{% set name = "lhorizon" %}
{% set version = "1.1.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/lhorizon-{{ version }}.tar.gz
  sha256: 56445f72c0104fa2c07fa654e47ab435bc8187fd17bc0d884b14fdf608117d25

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.11
    - setuptools
  run:
    - more-itertools
    - numpy
    - pandas
    - pyerfa
    - python >=3.11
    - python-dateutil
    - requests
    - sympy
    - spiceypy

test:
  imports:
    - lhorizon
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/millionconcepts/lhorizon.git
  summary: lhorizon helps you find things in the solar system
  description: lhorizon helps you find things in the Solar System. It is built around a thick Python wrapper for the Jet Propulsion Laboratory (JPL) Horizons service. Horizons, provided by JPL's Solar System Dynamics Group (SSD), is one of the only sources in the world that offers no-assembly-required high-precision data
    on the relative positions and velocities of almost every known body in the Solar System. lhorizon offers tools to query Horizons for data, parse its responses into useful Python objects, and smoothly incorporate them into bulk calculation and transformation workflows.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - m-stclair
